# Generated by Django 3.2 on 2021-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_result', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'result',
            },
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
