# Generated by Django 3.2 on 2021-06-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_auto_20210606_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'all_films',
            },
        ),
    ]
