# Generated by Django 3.2 on 2021-06-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_allfilms'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfilms',
            name='all_films_result',
            field=models.CharField(default=-1.0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='allfilms',
            table='all',
        ),
    ]
